behaviors:
  RacingAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512 #10 #128
      buffer_size: 4096 #100 #2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 8 #3
      learning_rate_schedule: linear
#      beta_schedule: constant
#      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256 #512
      num_layers: 2 #2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1 #1
    max_steps: 25000000
    time_horizon: 64
    summary_freq: 5000